// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CareConnect.Services.MentelHealthApi.Migrations
{
    [DbContext(typeof(MentelHealthApiContext))]
    [Migration("20241108185823_MentalHealth_FirstUpdate")]
    partial class MentalHealth_FirstUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CareConnect.Services.MentelHealthApi.Models.MoodTracker", b =>
                {
                    b.Property<DateTime>("DateTimeOfEntry")
                        .HasColumnType("datetime2")
                        .HasColumnName("EntryTime");

                    b.Property<string>("CurrentMood")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DoctorID")
                        .HasColumnType("int");

                    b.Property<bool>("History")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DateTimeOfEntry");

                    b.ToTable("MoodTracker");
                });
#pragma warning restore 612, 618
        }
    }
}
